---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: nginx
    project: roboshop
    service: frontend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      project: roboshop
      service: frontend
      env: dev
  template:
    metadata:
      labels:
        app: nginx
        project: roboshop
        service: frontend
        env: dev
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: nginx-conf
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: rkalluru/k06-frontend:340
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /data
          resources:
            limits:
              memory: 500Mi
              cpu: 250m
            requests:
              memory: 500Mi
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: nginx
    project: roboshop
    service: frontend
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;
    include /usr/share/nginx/modules/*.conf;
    events {
        worker_connections 1024;
    }
    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;
        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;
        include /etc/nginx/conf.d/*.conf;
    server {
        listen       80;
        server_name  localhost;
        proxy_http_version 1.1;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            ssi    on;
        }
        location /images/ {
            expires 5s;
            root   /usr/share/nginx/html;
            try_files $uri /images/placeholder.jpg;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }


        location /api/catalogue/ {
            proxy_pass http://catalogue:7001/;
        }

        location /api/user/ {
            proxy_pass http://user:7007/;
        }

        location /api/cart/ {
            proxy_pass http://cart:7000/;
        }

        location /api/shipping/ {
            proxy_pass http://shipping:7005/;
        }

        location /api/payment/ {
            proxy_pass http://payment:7002/;
        }


        location /nginx_status {
            stub_status on;
            access_log off;
        }
      }
    }